version: "3"
services:
  bookings-service:
    depends_on:
      - migrate
    image: bookings:local
    container_name: bookings-service
    ports:
      - 9999:8080
    environment:
      - REST_PORT=8080
      - PG_CONNECTION_STRING=postgres://myuser:mypassword@postgres:5432/bookings?sslmode=disable
      - SPACEX_BASE_URL=https://api.spacexdata.com/v4

  postgres:
    image: postgres:15
    container_name: bookings_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bookings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d bookings" ]
      interval: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://myuser:mypassword@postgres:5432/bookings?sslmode=disable",
      "up"
    ]
    volumes:
      - ./services/bookings/resources/database/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: