// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBooking = `-- name: CreateBooking :exec
INSERT INTO bookings (id, first_name, last_name, gender, birthday, launch_pad_id, destination_id, launch_date,
                      created_at, updated_at)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10)
`

type CreateBookingParams struct {
	ID            uuid.UUID
	FirstName     string
	LastName      string
	Gender        string
	Birthday      string
	LaunchPadID   string
	DestinationID string
	LaunchDate    time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) error {
	_, err := q.db.ExecContext(ctx, createBooking,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.Birthday,
		arg.LaunchPadID,
		arg.DestinationID,
		arg.LaunchDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT
    id, first_name, last_name, gender, birthday, launch_pad_id, destination_id, launch_date, created_at, updated_at
FROM
    bookings
WHERE
    id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.Birthday,
		&i.LaunchPadID,
		&i.DestinationID,
		&i.LaunchDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT
    id, first_name, last_name, gender, birthday, launch_pad_id, destination_id, launch_date, created_at, updated_at
FROM
    bookings
WHERE
    ($1::timestamptz IS NULL OR launch_date = $1)
  AND ($2::varchar IS NULL OR launch_pad_id = $2)
  AND ($3::varchar IS NULL OR destination_id = $3)
ORDER BY
    created_at DESC
    LIMIT $4 OFFSET $5
`

type ListBookingsParams struct {
	Column1 time.Time
	Column2 string
	Column3 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookings,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.Birthday,
			&i.LaunchPadID,
			&i.DestinationID,
			&i.LaunchDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
